$schema: "http://json-schema.org/draft-07/schema#"
description: config dictionary
type: object
properties:
    contig_fasta:
        type: string
        description: path to FASTA file with assembled contigs
    read_metadata:
        type: string
        description: path to tsv file with sequencing read metadata

required:
    - contig_fasta
    - read_metadata

