$schema: "http://json-schema.org/draft-07/schema#"
description: config dictionary
type: object
properties:
    contig-fasta:
        type: string
        format: uri
        description: path to FASTA file with assembled contigs
    read-metadata:
        type: string
        format: uri
        description: path to tsv file with sequencing read metadata
    iterations:
        type: integer
        description: how many rounds of polishing to run
        minimum: 1
    slice-size:
        type: integer
        description: number of bases that each FASTA slice should contain after splitting
        minimum: 50000
    pilon:
        type: object
        properties:
            java-memory:
                type: integer
                description: amount of memory (GB) that the JVM can use
                minimum: 1
            fix-errors:
                type: array
                description: what types of errors that pilon should attempt to fix
                items:
                    type: string
                    enum:
                        - snps
                        - indels
                        - bases
                        - gaps
                        - local
                        - all
                        - bases
                        - none
                        - amb
                        - breaks
                        - circles
                        - novel
        required:
            - java-memory
            - fix-errors
    cluster:
        type: object
        properties:
            cookiecutter:
                type: object
                properties:
                    url:
                        type: string
                        format: uri
                    profile_name:
                        type: string
                    cluster_config:
                        type: string
                        format: uri
                    advanced_argument_conversion:
                        type: boolean
            snakemake:
                properties:
                    use-conda:
                        type: boolean
                    use-envmodules:
                        type: boolean
                    restart-times:
                        type: integer
                        minimum: 0
                    jobs:
                        type: integer
                        minimum: 1
                    latency-wait:
                        type: integer
                        minimum: 0

required:
    - contig-fasta
    - read-metadata
    - iterations
    - slice-size
    - pilon
