$schema: "http://json-schema.org/draft-07/schema#"
description: config dictionary
type: object
properties:
    contig_fasta:
        type: string
        description: path to FASTA file with assembled contigs
    read_metadata:
        type: string
        description: path to tsv file with sequencing read metadata
    iterations:
        type: integer
        description: how many rounds of polishing to run
    slice_size:
        type: integer
        description: number of bases that each FASTA slice should contain after splitting
        minimum: 50000
    fix_errors:
        type: array
        description: what types of errors that pilon should attempt to fix
        items:
            type: string
            enum:
                - snps
                - indels
                - bases
                - gaps
                - local
                - all
                - bases
                - none
                - amb
                - breaks
                - circles
                - novel

required:
    - contig_fasta
    - read_metadata
    - iterations
    - slice_size
    - fix_errors

